name: Build and Release Flick

on:
  push:
    tags:
      - 'v*'  # trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

env:
  CMAKE_PRESET: ${{ matrix.os == 'windows-latest' && 'windows-static-build' || matrix.os == 'ubuntu-latest' && 'linux-static-build' || matrix.os == 'macos-latest' && 'osx-static-build' }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone vcpkg
        run: git clone https://github.com/microsoft/vcpkg.git vcpkg

      - name: Bootstrap vcpkg (Linux/macOS)
        if: runner.os != 'Windows'
        run: ./vcpkg/bootstrap-vcpkg.sh
        shell: bash

      - name: Bootstrap vcpkg (Windows)
        if: runner.os == 'Windows'
        run: .\vcpkg\bootstrap-vcpkg.bat

      - name: Set VCPKG_ROOT environment variable
        run: echo "VCPKG_ROOT=$(pwd)/vcpkg" >> $GITHUB_ENV

      - name: Configure CMake with preset
        run: cmake --preset $CMAKE_PRESET

      - name: Build with preset
        run: cmake --build --preset $CMAKE_PRESET --config Release

      - name: Prepare artifacts folder
        run: |
          mkdir -p artifacts
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            cp ./build/windows-static-build/flick/flick.exe artifacts/
            cp ./build/windows-static-build/flick/utool.exe artifacts/
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            cp ./build/osx-static-build/flick/flick artifacts/
            cp ./build/osx-static-build/flick/utool artifacts/
          else
            cp ./build/linux-static-build/flick/flick artifacts/
            cp ./build/linux-static-build/flick/utool artifacts/
          fi
        shell: bash

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flick-${{ matrix.os }}
          path: artifacts/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: flick-windows-latest
          path: artifacts/windows

      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: flick-ubuntu-latest
          path: artifacts/linux

      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: flick-macos-latest
          path: artifacts/macos

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}

      - name: Upload Windows binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/windows/flick.exe
            artifacts/windows/utool.exe

      - name: Upload Linux binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/linux/flick
            artifacts/linux/utool

      - name: Upload macOS binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/macos/flick
            artifacts/macos/utool
